# Generated by Django 4.0.4 on 2022-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ghj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
